### PR TITLE
1.16 support

### PR DESCRIPTION
**Pull request by Ingrim4**

### CODE REVIEW

**Review by NgLoader — DISMISSED** [review]

**Comment by qq59557445** [comment]
When can 1.16 be supported

**Review by Ofek270704 — COMMENTED** [review]
It does not work in version 1.16.1

**Comment by Ofek270704** [comment]
Please fix it fast I need it urgently to my server

**Comment by Ofek270704** [comment]
Whenever I put this plugin ordinary people see the world with holes and the anti xray doesn't work

**Comment by Ofek270704** [comment]
only in the overworld it does not work

**Comment by Ingrim4** [comment]
This is an **in-dev project** which is why 1.16 isn't supported fully. 1.16 support will be done when it's done! Be patient and don't write unconstructive/useless comments.

**Review by NgLoader — DISMISSED** [review]

**Review by NgLoader — APPROVED** [review]

**Pull request merged**
