### PR TITLE
[#376] Add support for 1.21

### LINKED ISSUE #376: Minecraft 1.21
### Description

Good morning, when will orebfuscator support version 1.21?

### Reproduction Steps

support version 1.21

### Expected Behaviour

fix the error as quickly as possible

### Orebfuscator Dump

i don't have :(

### Extra Details

_No response_

### PR DESCRIPTION
**Pull request by Ingrim4**
## Description
Add support for 1.21 and remove support for java versions before 17 and minecraft versions before 1.16.

## Related Issue
closes #376

## Motivation and Context
New game version release

## How Has This Been Tested?
Untested as of yet

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Review by NgLoader — DISMISSED** [review]

**Comment by AndyIsHereBoi** [comment]
will this be merged?

**Comment by Dezaku** [comment]
Need an update on this please

**Comment by AndyIsHereBoi** [comment]
These kids on my server started creating the first second they got lol

**Comment by Dezaku** [comment]
if you are on paper you can use the built in xray for now

> These kids on my server started creating the first second they got lol

**Comment by Ingrim4** [comment]
We will probably test stability of this update later today with all release since 1.16+. Until than you can simply use the dev builds from github: https://github.com/Imprex-Development/orebfuscator/actions/runs/9571627872/artifacts/1614470247

**Comment by AndyIsHereBoi** [comment]
Hopefully those are the nms errors I was having

**Review by NgLoader — APPROVED** [review]

**Pull request merged**
